const firstColor = "#80C23E" //cores de fundos 
const secondColor = "rgba (173,216,230, 0.9)" //cores de headers
const thirdColor = "rgb (0,250,154)" //cores de cards
const fourthColor = "rgb(144,238,144)"
const bordersColor = "white"
const selectedIconColor = "black"
const nonSelectedIcon = "white"
const  borderIconColor = "black"
export const colors = {firstColor, secondColor, thirdColor , fourthColor , bordersColor,selectedIconColor,nonSelectedIcon,borderIconColor}